[package]
name = "pallet-chainlink"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}
sp-runtime = { version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}
frame-support = { version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}
frame-system = { package = "frame-system", version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}
balances = { package = "pallet-balances", version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}

[dev-dependencies]
sp-core = { version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}
sp-io = { version = "2.0.0-rc6", tag = 'v2.0.0-rc6', default-features = false, git = 'https://github.com/paritytech/substrate.git'}

[features]
default = ["std"]
std = [
	"codec/std",
	'balances/std',
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
